### ISSUE TITLE
Make Propagation Compatible With Native Handlers

### ISSUE THREAD

**Issue by mecha** [Dhii/wp-events#11]
## The Symptom

The wrapped handlers are capable of detecting when an `EventInterface` stops propagation via `isPropagationStopped()`. Native handlers, however, have no such check; neither are they capable of implementing one since they do not even receive the event instance as argument.

This makes it impossible for a wrapped handler to be certain that no other handler will be executed for that event when there are native handlers that have yet to be executed.

## Recommended Solution

And most probably the _only_ solution.

A special handler can be attached to the `"all"` hook, making it trigger on all hooks. This handler can then create a wrapper for all native handlers. The wrapper handler already checks for propagation and halting if necessary, therefore solving the problem.

This should probably be an opt-in feature. Perhaps a `wrapWordPressHandlers()` method can be added to the manager that registers the special handler on the `all` hook.

**Comment by XedinUnknown** [comment]
@mecha, thank you for this report. Is it possible at all to implement the described solution?

**Comment by mecha** [comment]
@XedinUnknown From my research, it is possible _if and only if_ the special handler on the `all` hook can modify the native handlers. I have yet to confirm this.

**Comment by mecha** [comment]
## Update

I've been attempting to create a prototype solution for this and have discovered a couple of things:

1. If a native filter handler is declared with an argument _reference_, extra computation is required in the native handler's wrapper to make those arguments references before passing them on to the original handler. This is because (to my understanding) `func_get_args()` seems to be giving the _values_ passed. A simple `foreach` solution from a [StackOverflow thread][1] did the trick and did not detriment performance.

2. Accessing the event cache on each hook affected performance. Most pages were still able to load while others where running out of memory or timing out. This is mostly because of point 3, but I did manage to avoid accessing the cache on each hook by retrieving the cache only once for each hook type and making the wrappers for the native functions `use` the event instance.

3. Attaching a clear cache handler on each hook *heavily destroyed performance*. All pages were timing out and running out of memory. This does not seem to be caused by any form of recursion but because [`WP_Hook`][2] will [detect][3] if a new handler has been added to a hook that is currently being invoked and will [re-sort the handlers][4] to maintain their order by priority.

Removing the clear cache handler, I've concluded that the performance impact from everything else is very negligible. So perhaps we can revise our current clear cache mechanism and come up with a solution that does not attach a late handler and trigger [`resort_active_iterations()`][4].

[1]: http://stackoverflow.com/questions/29479579/combining-func-get-args-call-user-func-array-and-pass-by-reference
[2]: https://developer.wordpress.org/reference/files/wp-includes/class-wp-hook.php/
[3]: https://core.trac.wordpress.org/browser/tags/4.7/src/wp-includes/class-wp-hook.php#L93
[4]: https://developer.wordpress.org/reference/classes/wp_hook/resort_active_iterations/
