### ISSUE TITLE
Add PHP 8 support

### ISSUE THREAD

**Issue by strangerkir** [Dhii/wp-events#17]
Currently, this package [requires](https://github.com/Dhii/wp-events/blob/develop/composer.json#L15) PHP ^5.4 or PHP ^7.0.

It's needed to add PHP 8 support, otherwise, this package cannot be used in many projects. Optionally, PHP 5.x support can be dropped to make package support easier and allow using of new language features.

**Comment by XedinUnknown** [comment]
@strangerkir, please bring this in line with [`dhii/php-project`][]. This would mean dropping support for PHP 5. I suggest requiring at least PHP 7.2, as I cannot think of a new project that would require anything lower. Please aim the PR at [`0.4.x`][], and feel free to tackle #18 in the same PR. Don't forget about [Project Management][] 👍.

[`dhii/php-project`]: https://github.com/Dhii/php-project
[`0.4.x`]: https://github.com/Dhii/wp-events/tree/0.4.x
[Project Management]: https://github.com/orgs/Dhii/projects/3

**Comment by XedinUnknown** [comment]
@strangerkir, I would like to suggest also tackling #19 as part of the same PR.

**Comment by XedinUnknown** [comment]
Closed in favour of #21.
