### ISSUE TITLE
Stop using deprecated dhii/i18n-helper-base package

### ISSUE THREAD

**Issue by strangerkir** [Dhii/wp-events#18]
This package [requires](https://github.com/Dhii/wp-events/blob/develop/composer.json#L19) dhii/i18n-helper-base, [marked](https://github.com/dhii/i18n-helper-base#deprecated-dhii---internationalization-helper-base) as deprecated. Additionally, dhii/i18n-helper-base requires PHP ^7.0, which prevents us from [upgrading this package to use PHP 8](https://github.com/Dhii/wp-events/issues/17).

**Comment by XedinUnknown** [comment]
Closed in favour of #21.
