### ISSUE TITLE
EventInterface's setter methods should return void

### ISSUE THREAD

**Issue by szepeviktor** [Dhii/wp-events#19]
Event's setter methods return the instance.

https://github.com/Dhii/wp-events/blob/feee39e602709ae0e5d557d3ae48694d3c7310da/src/Event.php#L110-L118

Please advise.

**Comment by szepeviktor** [comment]
Similar return type differences in WpEventManager versus EventManagerInterface.

**Comment by XedinUnknown** [comment]
Heya, @szepeviktor! Thanks for pointing this out! This package is pending an update which will be released with a BC-breaking tag. The update will include PHP 8 support (#17), with all the relevant consequences. We will make sure that this is one of the things we do there.

**Comment by XedinUnknown** [comment]
Closed in favour of #21.
