### ISSUE TITLE
Event Always Created During Normalization

### ISSUE THREAD

**Issue by XedinUnknown** [Dhii/wp-events#2]
## The Problem
[`EventManager#normalizeEvent()`](https://github.com/Dhii/wp-events/blob/0.2/src/EventManager.php#L75) will always create a new `Event` instance.

## Possible Cause
The [check](https://github.com/Dhii/wp-events/blob/0.2/src/EventManager.php#L77) for input type will never pass, because class `EventInterfacevent` does not exist. However, this will also never result in an error, because `instanceof` does not require the interface to exist.

## Suggested Solution
Make `instanceof` check for the correct class name, [`EventInterface`](https://github.com/Dhii/psr-14/blob/master/src/EventInterface.php#L8).

**Comment by mecha** [comment]
Confirmed. Looks like one of my best typing errors yet 😆
